drop table if exists member CASCADE;
drop table if exists card CASCADE;
drop table if exists chat CASCADE;
drop table if exists gptChat CASCADE;
drop table if exists userChat CASCADE;

create table member
(
     id   bigint generated by default as identity,
     manager_name varchar(255),
     chat_id bigint,
     FOREIGN key (chat_id) REFERENCES chat(id),
     primary key (id)
);

create table card
(
     id   bigint generated by default as identity,
     companyName varchar(255),
     companyNumber varchar(255),
     companyImageUrl varchar(255),
     member_id bigint,
     FOREIGN key (member_id) REFERENCES member(id),
     primary key (id)
);

create table chat
(
     id   bigint generated by default as identity,
     name varchar(255),
     created_at TIMESTAMP,
     primary key (id)
);

create table gptChat
(
    id bigint generated by default as identity,
    chat_id bigint,
    message varchar(255),
    FOREIGN key (chat_id) REFERENCES chat(id),
    primary key(id)

);

create table userChat
(
    id bigint generated by default as identity,
    chat_id bigint,
    message varchar(255),
    FOREIGN key (chat_id) REFERENCES chat(id),
    primary key(id)
)